# -*- coding: utf-8 -*-

class GdfFields:
    PATH = "path"
    TITLE = "title"
    DEVELOPER = "developer"
    PUBLISHER = "publisher"
    TAGS = "tags"
    AGES = "ages"
    DESCRIPTION = "description"
    RELEASEDATE = "releasedate"
    PLAYERS = "players"
    RATING = "rating"
    COVER = "cover"
    SCREENSHOT = "screenshot"
    WHEEL = "wheel"
    MARQUEE = "marquee"
    VIDEO = "video"

class EsFields:
    NAME = "name",
    PATH = "path"
    RATING = "rating"
    DESC = "desc"
    IMAGE = "image"
    RELEASEDATE = "releasedate"
    DEVELOPER = "developer"
    PUBLISHER = "publisher"
    GENRE = "genre"
    PLAYERS = "players"
    KIDGAME = "kidgame"

class PegasusFields:
    GAME = "game"
    FILE = "file"
    DEVELOPER = "developer"
    PUBLISHER = "publisher"
    GENRE = "genre"
    DESCRIPTION = "description"
    RELEASE = "release"
    PLAYERS = "players"
    RATING = "rating"
    ASSETS_VIDEO = "assets.video"
    ASSETS_WHEEL = "assets.wheel"
    ASSETS_MARQUEE = "assets.marquee"
    ASSETS_BOXFRONT = "assets.boxfront"
    ASSETS_SCREENSHOT = "assets.screenshots"
