class GdfFields:
    TITLE = "title"
    DEVELOPER = "developer"
    PUBLISHER = "publisher"
    GENRE = "genre"
    AGES = "ages"
    DESCRIPTION = "description"
    RELEASE = "releasedate"
    PLAYERS = "players"
    RATING = "rating"
    CHECKSUM = "checksum"

class EsFields:
    NAME = "name",
    PATH = "path"
    RATING = "rating"
    DESC = "desc"
    IMAGE = "image"
    RELEASEDATE = "releasedate"
    DEVELOPER = "developer"
    PUBLISHER = "publisher"
    GENRE = "genre"
    PLAYERS = "players"
    KIDGAME = "kidgame"

class PegasusFields:
    GAME = "game"
    FILE = "file"
    DEVELOPER = "developer"
    PUBLISHER = "publisher"
    GENRE = "genre"
    DESCRIPTION = "description"
    RELEASE = "release"
    PLAYERS = "players"
    RATING = "rating"
    ASSETS_VIDEO = "assets.video"
    ASSETS_WHEEL = "assets.wheel"
    ASSETS_MARQUEE = "assets.marquee"
    ASSETS_BOXFRONT = "assets.boxfront"
    ASSETS_SCREENSHOT = "assets.screenshots"
